logging:
  level:
    root: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


spring:
  application:
    name: elkservice
  profiles:
    active: prod

grpc:
  client:
    notification-service:
      address: static://localhost:9090
      negotiation-type: plaintext